postinst: add fallback for non-root user derivation
This is breaking on Ubuntu 16.04.
https://askubuntu.com/questions/490620/difference-between-logname-and-logname/816161#816161
indicates known bug or even broken on purpose (
https://bugzilla.gnome.org/show_bug.cgi?id=747046 ).

My fallback is inspired by https://askubuntu.com/questions/424237/who-w-logname-broken-in-multiple-terminals/849469#849469

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -18,7 +18,17 @@ USER_CRON_JOB='@hourly /usr/sbin/anacron -s -t $HOME/.anacrontab -S $HOME/.anacr
 # This MDM package is installed via sudo, e.g. `sudo dpkg -i package.deb`.
 # Derive non-root user attributes since the MDM software will later run as
 # non-root.
-NON_ROOT_USER="$(logname)"
+get_non_root_user() {
+    NRU=$(logname 2>/dev/null || echo ${SUDO_USER})
+    if [[ -z "$NRU" ]] || [[ "$NRU" == 'root' ]]
+    then
+        echo 'Error, unable to derive non-root username'
+        exit 1
+    fi
+    echo "$NRU"
+}
+
+NON_ROOT_USER="$(get_non_root_user)"
 NON_ROOT_UID="$(id -u "$NON_ROOT_USER")"
 NON_ROOT_GID="$(id -g "$NON_ROOT_USER")"
 NON_ROOT_HOME="/home/$NON_ROOT_USER"
